# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anderson José Simplicio
title: Programador Python/Django e Cientista de Dados
email: anderson25eu@gmail.com
website: https://www.pjexperience.com.br/


# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username: andersonsimplicio
instagram_username: simplicioanderson
linkedin_username: anderson-simplicio-77081b50


# About Section
# about_title: About Me (Use this to override about section title)
about_title: Sobre
about_profile_image: images/profile.jpg
about_content: |
  Sou Pós-Graduando em Ciência de Dados pela Pontifícia Universidade Católica de Minas Gerais em 2021/2022. 
  Tecnologo em Sistemas para Internet pelo Instituto Federal de Educação Ciência e Tecnologia do Sudeste de Minas.
  Possuo experiência em programação back-end com framework Django e algumas atividades com Ciência de Dados 
  cuja a especialização está em fase de conclusão.

  Possuo o objetivo de formação na área de Inteligência Computacional, me permitindo criar sistemas web/mobile
  integrados com aplicações de Machine Learning.

  Meus estudos atuais:
       
    <i class="fab fa-linux" style="color:black;"></i> 
    <mark style="background-color:#5F9EA0;font-weight: bold;">Linux Desktop</mark>
    <mark style="background-color:#008080;font-weight: bold;">Servidores Linux</mark>
    

    <i style="color:#3499cd;" class="fab fa-python"></i> 
    <mark style="background-color:#000080;font-weight: bold;">Python</mark>
    <mark style="background-color:#4B0082;font-weight: bold;">Django</mark>
    <mark style="background-color:#002b51;font-weight: bold;">REST</mark>
    <mark style="background-color:#3499cd;font-weight: bold;">Scikit-learn</mark>
    <mark style="background-color:#3499cd;font-weight: bold;">Numpy</mark>
    <mark style="background-color:#3499cd;font-weight: bold;">Scipy</mark>
    <mark style="background-color:#0a5773;font-weight: bold;">Pandas</mark>

    <i class="fab fa-react" style="color:#287eb7;"></i>
    <mark style="background-color:#214ce5;font-weight: bold;">HTML</mark>
    <mark style="background-color:#214ce5;font-weight: bold;">CSS</mark>
    <mark style="background-color:#4682B4;font-weight: bold;">JavaScript</mark>
    <mark style="background-color:#287eb7;font-weight: bold;">React</mark>
    <mark style="background-color:#008B8B;font-weight: bold;">React-Native</mark>
    <mark style="background-color:#75ac64;font-weight: bold;">Nodejs</mark>
    

content:
  - title: <i class="fas fa-project-diagram"></i> Projetos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: PJExperience
        link: https://www.pjexperience.com.br/
        link_text: pjexperience
        additional_links:
          - title: Tecnologias
            icon: fab fa-python
          - title: Tecnologias
            icon: fab fa-linux
            
        quote: >
          Sistema de Simulação de processo Judicial Eletrônico 
        description: | 
          O Pjexperience foi inspirado no pje, Processo Judicial Eletrônico, é um sistema de tramitação de processos judiciais,
          sua finalidade é de criar um ambiente virtual simulado que permite estudantes em direito realizar todos os passos da 
          tramitação de processos judiciais, inclusive assumindo Papeis como: Magistrado, Advogado, MP.
           <br>
           <div style="text-align: center;">
           <img style="border-radius:5px" src="images/pjex.png" width=520px height=240px ><br>
           <hr>  
           </div>

      - layout: top-middle
        title: Híbrida
        link: http://hibrida.pjexperience.com.br/
        link_text: Híbrida
        additional_links:
          - title: Tecnologias
            icon: fab fa-python
          - title: Tecnologias
            icon: fab fa-linux

        quote: >
          É um projeto que tem por objetivo assegurar a redução no lapso temporal da tramitação dos processos 
        description: | 
          concretizando os princípios da eficiência e eficácia administrativa, celeridade processual e acesso à justiça.
          Garante o incremento da agilidade, identificando o assunto de tema repetitivo 1007 do STJ, associando-o ao respectivo 
          código de assunto do Conselho Nacional de Justiça – CNJ e dos tribunais locais quando disponibilizados ao público.
          O presente projeto visa atender as demandas propostas pelo desafio 1 TEMPO E PRODUTIVIDADE do edital CNJ INOVA fase 1.<br>
          <div style="text-align: center;">
          <img style="border-radius:5px" src="https://user-images.githubusercontent.com/37173966/96740018-cec57000-1396-11eb-8f6d-cb90afb63760.jpeg" width=320px height=240px ><br><hr>
          </div>
      - layout: top-middle
        title: MapaJud 
        link: https://github.com/andersonsimplicio/geocrimeambiental
        link_text: MapaJud  
        additional_links:
          - title: Tecnologias
            icon: fab fa-python
          - title: Tecnologias
            icon: fab fa-linux
                  
        quote: >     
          LIODS CNJ - Inovação, Inteligência e Objetivos de Desenvolvimento Sustentável
        description: |       
         MapaJud indexa o número único do processo de terras públicas ao código do SireneJud exibindo inclusive outras
         bases de dados de georreferenciamento como INCRA, Sistema de Gestão Fundiária (SIGEF), Cadastro Ambiental Rural (CAR),
         Serviço Florestal Brasileiro (SFB), e se aprenta como demonstrado da figura.
          <br>
          <div style="text-align: center;">
          <img style="border-radius:5px" src="images/mapajud.png" width=520px height=240px ><br>
          <hr>  
          </div>
      - layout: top-middle
        title: PetShop app
        link: https://github.com/andersonsimplicio/pestshop
        link_text: PetShop
        additional_links:
          - title: Tecnologias
            icon: fab fa-react
          - title: Tecnologias
            icon: fab fa-linux                      
        quote: >
          Um app com intuito de atender demandas de um PetShop para agendamento de serviços
        description: | 
          Este de projeto de App para petshop foi utilizado no processo de aprendizagem do react-native e expo <br>
          <div style="text-align: center;">
          <img style="border-radius:5px" src="https://github.com/andersonsimplicio/pestshop/raw/main/assets/TelaExemplo.png?raw=true" width=520px height=340px ><br>
          </div>
  - title: <i class="fas fa-business-time"></i> Experiência
    layout: list
    content:
      - layout: right
        title: Senac Minas 
        sub_title: Orientador de Cursos
        caption: Janeiro 2013 - Novembro 2020
        link: https://www.mg.senac.br/
        quote: >
          A Instituição é referência em educação profissional na área de comércio de bens, serviços e turismo.
          O Senac oferece, nas modalidades presencial e a distância, cursos livres e técnicos, além de graduação e MBA . 
        description: | 
          Cursos de atuação no <strong style="font-weight: bold;">Senac</strong>:
          
          - Técnico em Redes de Computador com destaque para disciplina de Servidores Linux, na qual tinha paixão em lecionar
            e quase sempre concluíamos o livro de Servidores Linux - Guia Prático (Carlos E. Morimoto).
          
          - Técnico em Desenvolvimento de Sistemas Com destaque para as disciplinas de Lógida de Programação considerada por 
            min com a disciplina base do curso.

      - layout: right
        title: Universidade de Uberaba
        sub_title: Prof. de Práticas Laboratoriais
        caption: Janeiro 2012 - Julho 2021
        link: https://uniube.br/
        quote: >
          A história da hoje Universidade de Uberaba, Instituição sem fins lucrativos, mantida pela Sociedade Educacional 
          Uberabense, remonta ao ano de 1940, quando Mário Palmério funda o Lyceu do Triângulo Mineiro, com sede, inicialmente,
          na Rua Manoel Borges.  

        description: | 
          Cursos de atuação no <strong style="font-weight: bold;">Uniube</strong>:

          Na universidade de Uberaba, ministrava aulas de práticas laboratoriais de lógica de programação,
          linguagem técnica de programação, métodos, ferramentas computacionais e tecnologicas, para os cursos
          de Engenharias Elétrica e Civil.


  - title: <i class="fas fa-graduation-cap"></i> Formação
    layout: list
    content:
      - layout: top-right
        title: Instituto Federal de Educação, Ciência e Tecnologia do Sudeste de Minas Gerais
        sub_title: Curso Superior de Tecnologia em Sistemas para Internet
        caption: 2007 - 2010
        quote: >
           O Instituto Federal do Sudeste de Minas Gerais (IF Sudeste MG) é uma instituição pública e gratuita que
           enfatiza ao máximo tudo aquilo que possa tornar a sociedade mais justa, qualificada e participativa.
        description: | # this will include new lines to allow paragraphs
           Tecnologia em Sistemas para Internet visa à formação de recursos humanos para atuarem no desenvolvimento
           de soluções técnicas relacionadas à Internet, dando forte ênfase à utilização de laboratórios,
           para capacitar os alunos no uso eficiente dessas tecnologias. O tecnólogo em Sistemas para Internet
           é um profissional que pode atuar de forma autônoma, nos limites de sua responsabilidade técnica, junto a 
           indústrias, empresas comerciais ou instituições governamentais que utilizem tecnologias de informação, 
           podendo atuar em diversas atividades ligadas a planejamento, projetos, comercialização, implantação, operação
           e manutenção de sistemas de Informática, bem como continuar seus estudos em cursos de pós-graduação ou seguir a área de 
           pesquisa científica, trabalhando em instituições de pesquisa ou ensino voltadas para novas tecnologias na área de
           Sistemas para Internet.

      - layout: top-right
        title: Pontifícia Universidade Católica de Minas Gerais
        sub_title: Ciência de Dados e Big Data
        caption: 2021 - 2022
        quote: >
          Considerada uma das melhores universidades privadas do Brasil – é a única instituição privada de Minas Gerais 
          a fazer parte do ranking das melhores universidades do mundo: o Times Higher Education e eleita por seis vezes
          pelo Guia do Estudante, publicação da Editora Abril, como a melhor entre as particulares do país -  
          a PUC Minas é reconhecida pela Congregação para a Educação Católica, do Vaticano, como a maior universidade 
          católica do mundo, abrigando mais de 85 mil alunos em cursos de graduação e pós-graduação.
        description: | # this will include new lines to allow paragraphs
          O crescimento do mercado para as atividades de business analytics e para as tecnologias de Big Data é real 
          e as previsões são ainda mais promissoras. Isso, por consequência, já direciona para uma demanda efetiva por
          novos profissionais como o Cientista de Dados que devem ter competências e habilidades para entender bem as 
          estratégias e necessidades do negócio e gerenciar, projetar e desenvolver soluções de análise em grandes volumes
          de dados. 

          O curso é direcionado para formar esse profissional. Através de disciplinas teóricas e práticas, os alunos são conduzidos 
          a estudar e experimentar os conceitos, vivenciando a aplicação de técnicas para desenvolvimento de projetos relacionados 
          a Ciência de Dados e Big Data com o intuito de gerar valor para os negócios. 
 
  
  - title: <i class="fab fa-old-republic"></i> Mais sobre Min
    layout: text
    content: | # this will include new lines to allow paragraphs
      Gosto de desavios que estimule tudo que aprendi, mas que me chama para novos conhecimentos, por sempre busco oportunidades
      de fazer o diferencial. durante minha formação busquei completa integração com a comunidade academica e em conjunto contruímos
      e participamos de novos desafios.

      - <strong style="font-weight: bold;">Maratona de Programação da Sociedade Brasileira de Computação (SBC)</strong>
        
        Data: 20/09/2008 - duração 9 Horas
        
        Local: Universidade Salgado de Oliveira
        
        Campus Juiz de Fora - Av. dos Andradas, 731 – Morro da Glória
        
        Juiz de Fora/MG - CEP: 36036-000
        
        Telefone:(32) 3311-9900

      - <strong style="font-weight: bold;">Maratona de Programação da Sociedade Brasileira de Computação (SBC)</strong>
        
        Data: 19/09/2009 - duração 9 Horas

        Local: Universidade Salgado de Oliveira
        
        Campus Juiz de Fora - Av. dos Andradas, 731 – Morro da Glória
        
        Juiz de Fora/MG - CEP: 36036-000
        
        Telefone:(32) 3311-9900  



      - <strong style="font-weight: bold;"> O Profissional de TI na era da Internet. </Strong>

        Data: 18/02/2009
      
        Local: Instituto Federal de Educação Ciência e Tecnologia do Sudeste de Minas - Campus Barbacena.
      
      - <strong style="font-weight: bold;">IV LINUX DAY- Software Livre</strong>
        
        Data: 07/11/2009 - duração 10 Horas
        
        Local: Instituto Vianna Júnior
        
        Av. dos Andradas, 415 - CEP 36036-000 - Centro - Juiz de Fora – MG viannajr@viannajr.edu.br
        


 

# Footer
footer_show_references: true
references_title: <i class="fas fa-jedi" style="color:#287eb7;"></i>
                  

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
